
# login_username : 登陆发件人用户名

# login_password : 登陆发件人密码

# host:port : 发件人邮箱对应的host和端口，如：smtp.163.com:25 和 smtp.qq.com:465，暂时不用输入端口

# receiver : 收件人，支持多方发送，格式（注意英文逗号）： 123456789@163.com,zxcvbnm@qq.com

SMTP:
  login_username: jenkins@qq.com
  login_password: Jenkins123456
  host: smtp.exmail.qq.com
  port:
  receiver: 289967396@qq.com